version: '3.3'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - postgres_web_db
    command: npm run start:dev

  postgres_web_db:
    container_name: postgres_web_db
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - "5433:5433"
    expose:
      - "5433"
    environment:
      POSTGRES_USER: puser
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: bebs
      POSTGRES_PORT: 5433
    command: -p 5433
